#!/bin/bash


cd afxdp/mtcp_xdp_pktio/
make clean
make

cd ../../


cd afxdp/common/
make clean
make

cd ../libbpf/src/
make clean
make

cd ../../../

cd mtcp/src/
./compile

cd ../../

cd util/
make clean
make

cd ../

cd apps/example/
make clean
make

cd ../../
