#!/bin/bash

cd afxdp/libbpf/src/
make clean
make
sudo make install

cd ../../mtcp_xdp_pktio/
make clean
make

cd ../common/
make clean
make

cd ../../

cd mtcp/src/
./compile

cd ../../

cd util/
make clean
make

cd ../

cd apps/example/
make clean
make

cd ../../
